apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dmarc.fullname" . }}-config
  labels:
    {{- include "dmarc.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
