{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dmarc.fullname" . }}-backend
  labels:
    {{- include "dmarc.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dmarc.backend.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dmarc.fullname" . }}-frontend
  labels:
    {{- include "dmarc.frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dmarc.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
