apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmarc.fullname" . }}-backend
  labels:
    {{- include "dmarc.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dmarc.backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmarc.fullname" . }}-frontend
  labels:
    {{- include "dmarc.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dmarc.frontend.selectorLabels" . | nindent 4 }}
